# Page settings

baseURL = "https://ralang2005resume.netlify.app/"
languageCode = "en"
title = "Ryan Lang's Resume"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Ryan Lang"
    description = "Official Resume"
    og_image = "Original.jpg"
    twitterName = "@rlang05"
    ghRepo = ""
    hugoRepo = ""

    [params.profile]
        enable = true
        name = "Ryan Lang"
        tagline = "Resume"
        avatar = "Screenshot_20230826-003112_Discord.jpg"

    [params.contact]
        enable = true

        location = "North Carolina"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "(917)-535-5264"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ralang2005@gmail.com"
        text = "ralang2005@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ralang@my.waketech.edu"
        text = "ralang@my.waketech.edu"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Word and Powerpoint"
        [[params.skills.list]]
        title = "Keyboarding"
        [[params.skills.list]]
        title = "Semi-advanced Computer Proficiency"
        [[params.skills.list]]
        title = "Well-Organized and Kept"
        [[params.skills.list]]
        title = "Works well alone and in teams"


    [params.education]
        enable = true
        [[params.education.list]]
        degree = "Enrolled in"
        university = "Wake Tech Community College"
        dates = "2022/23-Present"
        [[params.education.list]]
        degree = "Student at"
        university = "Apex High School"
        dates = "2019-2023"
        [[params.education.list]]
        degree = "Graduated from"
        university = "Salem Middle School"
        dates = "2017-2019"
        [[params.education.list]]
        degree = "Graduated from"
        university = "Turner Creek Elementary"
        dates = "2016"
        [[params.education.list]]
        degree = "Temporarily Enrolled at"
        university = "Salem Elementary School"
        dates = "2014-2016"
        

    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Honor Roll"
        body = "scrum.org"
        date = ""


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Fluent"

        [[params.languages.list]]
        name = "Spanish"
        level = "Limited knowledge, took two high school classes"
        
        [[params.languages.list]]
        name = "French"
        level = "Learning, bare minimum knowledge"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Badminton"
        [[params.interests.list]]
        name = "Marketing"
        [[params.interests.list]]
        name = "Website Creation and Design"
        [[params.interests.list]]
        name = "Selling Items and Collectibles Online"
        [[params.interests.list]]
        name = "Music"


    [params.summary]
        enable = true
        text = "Apex High School Graduate, attending Wake Tech Community College pursuing an Associates in Science until 2025 transfer to UNC Charlotte for a major in Business Marketing"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Graduated AOIT Member"
        dates = "2019-2023"
        company = "Academy of Information & Technology"
        details = "A program that entails more computer related challenges and promised a better high school experience"
        [[params.experience.list.items]]
        details = "I joined through a lottery program and wrote an essay before graduating middle school, focusing on technical work like programming and web design classes."
        [[params.experience.list]]
        title = "Dogsitting"
        dates = "2018-Present"
        company = "Independently Operated by Yours Truly"
        details = "Watching pets for neighbors and family members"
        [[params.experience.list.items]]
        details = "Caring for neighbors' and family members' pets, mostly dogs, in 2018, imbued me with a sense of responsibility and nurtured qualities like kindness, respect, and reliability, shaping the trustworthy and caring person I am today."
        [[params.experience.list]]
        title = "Brown Bag Ministry Volunteer"
        dates = "2018"
        company = "Brown Bag Ministry in Central NC in association with St. Michael the Archangel Roman Catholic Church"
        details = "Around Thanksgiving, My local church hosted a brown bag ministry event where you would fill bags with food to give to those who were less fortunate in the spirit of giving."
        [[params.experience.list.items]]
        details = "Unlike previous instances of being compelled by parents or teachers, this was among the initial events in my life that I eagerly volunteered for. It underlined the importance of seizing opportunities, especially those that allow us to assist those in need, emphasizing the value of actively participating in such endeavors."
        [[params.experience.list]]
        title = "AOIT Job Shadow Experience"
        dates = "2019"
        company = "Academy of Information & Technology & Green Hope Elementary School"
        details = "Shadow a job of your choice and report your findings"
        [[params.experience.list.items]]
        details = "Collaborating with a teacher showed me the significance of patience in certain scenarios, highlighting the need to remain composed rather than becoming easily annoyed. It also underscored that even if not extensively developed, shared interests can foster positive relationships and understanding with others."
        [[params.experience.list]]
        title = "Miracle League of the Triangle Assistant/Volunteer"
        dates = "2019"
        company = "Miracle League of the Triangle with St. Michael the Archangel Roman Catholic Church"
        details = "Miracle League hosts baseball games where volunteers sign up to assist players who have special needs so that they can have some fun playing sports without having to worry about not knowing what to do or not having help."
        [[params.experience.list.items]]
        details = "Through my involvement with the Miracle League, I learned the value of patience, realizing that the focus didn't always have to be on winning or hitting home runs; instead, it emphasized the importance of having fun and cherishing the moments spent with others."
        [[params.experience.list]]
        
[params.projects]
        enable = true

        [[params.projects.list]]
        title = "Travel and Tourism Project"
        meta = "Academy of Information & Technology Project"
        url = "google.com"
        tagline = "Receive a budget to organize a delightful group vacation to a country of your choosing, while meticulously recording expenses and tracking expenditure."
        [[params.projects.list]]
        title = "AOIT Internship and Senior Presentation"
        meta = "Academy of Information & Technology Project"
        url = "google.com"
        tagline = "Similar to a job shadowing experience, this entails interning for a business, engaging in assigned tasks, and gaining paid hands-on experience."


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Family History"
        [[params.information.list.items]]
        details = "Born in Brooklyn, New York, in 2005, I relocated to Cary, North Carolina, at the age of 9 in 2014. Currently residing here with two dogs: Murphy and Gizmo, two shih tzus."
        [[params.information.list]]
        title = "Hobbies"
        [[params.information.list.items]]
        details = "My hobbies include listening to my favorite music, bowling at Buffaloe Lanes, and recently, excelling at playing badminton, a sport I picked up last year."

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ralang2005"
        title = "/ralang2005"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/ralang2005"
        title = "WIP: /in/ralang2005"
        [[params.social.list]]
        icon = "fab fa-instagram-square"
        url = "https://instagram.com/r.lang05"
        title = "@r.lang05"
